/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // VibeStudio brand colors inspired by Windsurf
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        secondary: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
          950: '#4a044e',
        },
        accent: {
          50: '#fefce8',
          100: '#fef9c3',
          200: '#fef08a',
          300: '#fde047',
          400: '#facc15',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
          950: '#422006',
        },
        vscode: {
          'editor-background': '#1e1e1e',
          'editor-foreground': '#d4d4d4',
          'activity-bar-background': '#333333',
          'activity-bar-foreground': '#ffffff',
          'activity-bar-inactive-foreground': '#ffffff66',
          'activity-bar-badge-background': '#007acc',
          'activity-bar-badge-foreground': '#ffffff',
          'sidebar-background': '#252526',
          'sidebar-foreground': '#cccccc',
          'sidebar-border': '#333333',
          'sidebar-title-foreground': '#bbbbbb',
          'sidebar-section-header-background': '#00000000',
          'sidebar-section-header-foreground': '#bbbbbb',
          'list-active-selection-background': '#094771',
          'list-active-selection-foreground': '#ffffff',
          'list-inactive-selection-background': '#37373d',
          'list-hover-background': '#2a2d2e',
          'list-focus-background': '#062f4a',
          'list-highlight-foreground': '#00ff00',
          'editor-group-header-tabs-background': '#252526',
          'tab-active-background': '#1e1e1e',
          'tab-inactive-background': '#2d2d2d',
          'tab-active-foreground': '#ffffff',
          'tab-inactive-foreground': '#ffffff80',
          'tab-border': '#252526',
          'tab-active-border': '#ffffff',
          'status-bar-background': '#007acc',
          'status-bar-foreground': '#ffffff',
          'status-bar-no-folder-background': '#68217a',
          'status-bar-debugging-background': '#cc6633',
          'panel-background': '#1e1e1e',
          'panel-border': '#333333',
          'terminal-background': '#1e1e1e',
          'terminal-foreground': '#cccccc',
          'terminal-ansi-bright-black': '#666666',
          'terminal-ansi-bright-red': '#f44747',
          'terminal-ansi-bright-green': '#60f360',
          'terminal-ansi-bright-yellow': '#f8f855',
          'terminal-ansi-bright-blue': '#6871ff',
          'terminal-ansi-bright-magenta': '#ff77ff',
          'terminal-ansi-bright-cyan': '#60f3f3',
          'terminal-ansi-bright-white': '#e5e5e5',
          'terminal-ansi-black': '#000000',
          'terminal-ansi-red': '#cd3131',
          'terminal-ansi-green': '#0dbc79',
          'terminal-ansi-yellow': '#e5e510',
          'terminal-ansi-blue': '#2472c8',
          'terminal-ansi-magenta': '#bc3fbc',
          'terminal-ansi-cyan': '#11a8cd',
          'terminal-ansi-white': '#e5e5e5',
        },
        // Status colors
        success: {
          50: '#f0fdf4',
          500: '#22c55e',
          600: '#16a34a',
        },
        warning: {
          50: '#fffbeb',
          500: '#f59e0b',
          600: '#d97706',
        },
        error: {
          50: '#fef2f2',
          500: '#ef4444',
          600: '#dc2626',
        },
        info: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Monaco', 'Consolas', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in-out',
        'fade-out': 'fadeOut 0.2s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'slide-out': 'slideOut 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOut: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glow': '0 0 20px rgba(14, 165, 233, 0.5)',
        'glow-lg': '0 0 40px rgba(14, 165, 233, 0.3)',
        'inner-lg': 'inset 0 2px 8px 0 rgba(0, 0, 0, 0.1)',
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
  darkMode: 'class',
};